!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!								!
!	Copyright 2001, 2009 Fidelity Information Services, Inc	!
!								!
!	This source code contains the intellectual property	!
!	of its copyright holder(s), and is made available	!
!	under a license.  If you do not know the terms of	!
!	the license, please stop and do not read further.	!
!								!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	.FACILITY	CMI,250/PREFIX=CMI_
	.TITLE	CMIERRORS Error Messages for CMI..GT.CM

DCNINPROG	<Attempt to initiate operation while disconnect was in progress>/fatal/fao=0
LNKNOTIDLE	<Attempt to initiate operation before previous operation completed>/fatal/fao=0
ASSERT		<Assert failed !AD line !UL>/error/fao=3
CMICHECK	<Internal CMI error. Report to your GT.M Support Channel.>/fatal/fao=0
NETFAIL		<Failure of Net operation>/error/fao=0

	.end
