!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!								!
!	Copyright 2001 Sanchez Computer Associates, Inc.	!
!								!
!	This source code contains the intellectual property	!
!	of its copyright holder(s), and is made available	!
!	under a license.  If you do not know the terms of	!
!	the license, please stop and do not read further.	!
!								!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	.FACILITY	GTCM,249/PREFIX=CMERR_
	.TITLE	CMERRORS	Error Messages for GTCM, VAX/VMS EDITION
INVPROT		<Invalid protocol specified by remote partner>/error/fao=0
REGNTFND	<Region referenced not initialized>/error/fao=0
CMINTQUE	<Interlock failure accessing GT.CM server queue>/fatal/fao=0
INVINTMSG	<Invalid interrupt message received.>/error/fao=0
CMEXCDASTLM	<Exceeded AST limit. Cannot open database.>/error/fao=0
CMSYSSRV	<Error doing system service, status:>/error/fao=0
	.end
