;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
; Generated by scantypedefs.m at 11:59:07 on 2019-10-23
; Build done with GT.M version: GT.M V6.3-010 Linux x86_64
;
; Environment variables during run:
;   $gtm_dist: /usr/library/V63010/dbg
;   $gtm_exe: /usr/library/V63010/dbg
;   $gtm_src: /usr/library/V63010/src
;   $gtm_inc: /usr/library/V63010/inc
;
; Note this file should not be manually invoked
;
	Write "GTM-E-GTMSDFILE This routine (",$TEXT(+0),") should not be manually invoked",!
	Quit
;
; Entry point used by gdeinit.m to define GTM structure fields
;
Init
	; GT.M structure and field definitions
	Set SIZEOF("gvstats")=472
	Quit
