;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
<<<<<<< HEAD
=======
; Generated by scantypedefs.m at 10:57:53 on 2018-11-01
; Build done with GT.M version: GT.M V6.3-005 Linux x86_64
;
; Environment variables during run:
;   $gtm_dist: /usr/library/V63005/dbg
;   $gtm_exe: /usr/library/V63006/dbg
;   $gtm_src: /usr/library/V63006/src
;   $gtm_inc: /usr/library/V63006/inc
;
>>>>>>> 74ea4a3c... GT.M V6.3-006
; Note this file should not be manually invoked
;
	Write "This routine (",$TEXT(+0),") should not be manually invoked",!
	Quit
;
; Entry point used by gdeinit.m to define YottaDB structure fields
;
Init
	; YottaDB structure and field definitions
	Set SIZEOF("gvstats")=472
	Quit
