;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
; Generated by scantypedefs.m at 15:27:52 on 2017-03-08
; Build done with GT.M version: GT.M V6.3-000A Linux x86
;
; Environment variables during run:
;   $gtm_dist: /usr/library/V63000A/dbg
;   $gtm_exe: /usr/library/V63001/dbg
;   $gtm_src: /usr/library/V63001/src
;   $gtm_inc: /usr/library/V63001/inc
;
; Note this file should not be manually invoked
;
	Write "GTM-E-GTMSDFILE This routine (",$TEXT(+0),") should not be manually invoked",!
	Quit
;
; Entry point used by gdeinit.m to define GTM structure fields
;
Init
	; GT.M structure and field definitions
	Set SIZEOF("gvstats")=472
	Quit
