/****************************************************************
 *								*
 *	Copyright 2001 Sanchez Computer Associates, Inc.	*
 *								*
 *	This source code contains the intellectual property	*
 *	of its copyright holder(s), and is made available	*
 *	under a license.  If you do not know the terms of	*
 *	the license, please stop and do not read further.	*
 *								*
 ****************************************************************/

#define LBR$C_CTLTBLID	203
#define LBR$M_LOCATE	1
#define LBR$M_OPEN	2
#define LBR$K_LENGTH	30
#define LBR$C_LENGTH	30
#define LBR$S_LBRCTLTBL	30
#define LBR$B_ID	0
#define LBR$B_TBLSIZ	1
#define LBR$B_TYPE	2
#define LBR$B_FUNC	3
#define LBR$R_USRFLG_OVERLAY	6
#define LBR$L_USRFLG	6
#define LBR$R_USRFLG_BITS	6
#define LBR$V_LOCATE	0
#define LBR$V_OPEN	1
#define LBR$L_HDRPTR	10
#define LBR$L_CTXPTR	14
#define LBR$L_CURIDX	18
#define LBR$L_USRNAM	22
#define LBR$L_OLDHDRPTR	26
#define LBR$C_TYP_UNK	0
#define LBR$C_TYP_OBJ	1
#define LBR$C_TYP_MLB	2
#define LBR$C_TYP_HLP	3
#define LBR$C_TYP_TXT	4
#define LBR$C_TYP_SHSTB	5
#define LBR$C_TYP_DECMX	5
#define LBR$C_TYP_RDEC	127
#define LBR$C_TYP_USRLW	128
#define LBR$C_TYP_USRHI	255
#define LBR$C_FLUSHDATA	1
#define LBR$C_FLUSHALL	0
#define LBR$C_MAXRECSIZ	2048
#define LBR$C_PAGESIZE	512
#define LBR$C_HASHSIZE	512
#define LBR$C_TEXTPAGE	508
#define LBR$C_DEXTQ	50
#define LBR$C_MAXCTL	16
#define LBR$C_MAXHDRSIZ	128
#define LBR$C_DEFENTALL	300
#define LBR$C_RETRYOPEN	30
#define LBR$C_RETRYWAIT	1
#define LBR$C_MINREAD	2
#define LBR$C_MAXREAD	50
#define LBR$C_MEMXTRA	50
#define LBR$C_PUTBUFSIZ	30
#define LBR$C_FLSHBFSIZ	1
#define LBR$C_MAXIDXRD	20
#define LBR$C_MAXKEYLEN	128
#define LBR$C_MAXLUHREC	32768
#define LBR$C_CREATE	0
#define LBR$C_READ	1
#define LBR$C_UPDATE	2
#define LBR$C_MAXFUNC	2
#define LBR$S_LBRDEF	16
#define LBR$L_IC_CTLTBL	4
#define LBR$L_IC_FUNC	8
#define LBR$L_IC_TYPE	12
#define LBR$S_LBRDEF1	32
#define LBR$L_OP_CTLTBL	4
#define LBR$L_OP_FNS	8
#define LBR$L_OP_CREOPT	12
#define LBR$L_OP_DNS	16
#define LBR$L_OP_RLFNA	20
#define LBR$L_OP_RNS	24
#define LBR$L_OP_RNSLEN	28
#define LBR$S_LBRDEF2	8
#define LBR$L_CL_CTLTBL	4
#define LBR$S_LBRDEF3	12
#define LBR$L_GH_CTLTBL	4
#define LBR$L_GH_RETARY	8
#define LBR$S_LBRDEF4	12
#define LBR$L_SI_CTLTBL	4
#define LBR$L_SI_IDXNUM	8
#define LBR$S_LBRDEF5	16
#define LBR$L_LK_CTLTBL	4
#define LBR$L_LK_KEYNAM	8
#define LBR$L_LK_TXTRFA	12
#define LBR$S_LBRDEF6	16
#define LBR$L_IK_CTLTBL	4
#define LBR$L_IK_KEYNAM	8
#define LBR$L_IK_TXTRFA	12
#define LBR$S_LBRDEF7	20
#define LBR$L_RK_CTLTBL	4
#define LBR$L_RK_KEYNAM	8
#define LBR$L_RK_OLDRFA	12
#define LBR$L_RK_NEWRFA	16
#define LBR$S_LBRDEF8	12
#define LBR$L_DK_CTLTBL	4
#define LBR$L_DK_KEYNAM	8
#define LBR$S_LBRDEF9	12
#define LBR$L_DD_CTLTBL	4
#define LBR$L_DD_TXTRFA	8
#define LBR$S_LBRDEF10	16
#define LBR$L_GR_CTLTBL	4
#define LBR$L_GR_BUFDES	8
#define LBR$L_GR_BUFLEN	12
#define LBR$S_LBRDEF11	16
#define LBR$L_PR_CTLTBL	4
#define LBR$L_PR_BUFDES	8
#define LBR$L_PR_TXTRFA	12
#define LBR$S_LBRDEF12	8
#define LBR$L_PE_CTLTBL	4
#define LBR$S_LBRDEF13	20
#define LBR$L_SR_CTLTBL	4
#define LBR$L_SR_IDXNUM	8
#define LBR$L_SR_RFA	12
#define LBR$L_SR_USRTN	16
#define LBR$S_LBRDEF14	12
#define LBR$L_SU_KEYDES	4
#define LBR$L_SU_TXTRFA	8
#define LBR$S_LBRDEF15	16
#define LBR$L_GI_CTLTBL	4
#define LBR$L_GI_IDXNUM	8
#define LBR$L_GI_USRTN	12
#define LBR$S_LBRDEF16	12
#define LBR$L_GU_KEYADR	4
#define LBR$L_GU_TXTRFA	8
#define LBR$C_ADDMOD	1
#define LBR$C_DELMOD	2
#define LBR$C_REPMOD	3
#define LBR$S_LBRDEF17	16
#define LBR$L_AU_CTLTBL	4
#define LBR$L_AU_FLAGS	8
#define LBR$L_AU_KEYNAM	12
#define LBR$S_LBRDEF18	12
#define LBR$L_GU_CTLTBL	4
#define LBR$L_GU_USRTN	8
#define LBR$S_LBRDEF19	8
#define LBR$L_UU_UPDESC	4

#define LBR$_HDRTRUNC 0x00268800
