!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!								!
!	Copyright 2001 Sanchez Computer Associates, Inc.	!
!								!
!	This source code contains the intellectual property	!
!	of its copyright holder(s), and is made available	!
!	under a license.  If you do not know the terms of	!
!	the license, please stop and do not read further.	!
!								!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	.FACILITY	GTLP,240/PREFIX=LP_
	.TITLE	LPERRORS	 Messages for GTLP, VMS EDITION
NOCNFDB <No configuration data base>/fao=0/fatal
NOCONF <No configuration for the product>/fao=1/fatal
NOVERS <No configuration for the product version>/fao=0/fatal
LEXPIR <The configuration has expired>/fao=0/fatal
NOAVAL <The configuration is not yet available>/fao=0/fatal
INVCSM <Invalid configuration>/fao=0/fatal
NOTACQ <No configuration units acquired>/fao=0/fatal
BADRES <Bad resource>/fao=0/fatal
JOBLIM <Job limit exceeded>/fao=0/fatal
	.END
